from BaseClasses import Region, Entrance, ItemClassification, Location, LocationProgressType
from .locations import ChibiRoboLocation, LOCATION_TABLE, ChibiRobobLocationData
from typing import Dict, List, NamedTuple, Optional

from BaseClasses import MultiWorld, Region, Entrance


class ChibiRoboRegionData(NamedTuple):
    locations: List[str]
    region_exits: Optional[List[str]]

def create_regions(multiworld: MultiWorld, player: int, options):
    regions: Dict[str, ChibiRoboRegionData] = {
        "Menu": ChibiRoboRegionData([], ["Menu - Living Room" ]),
        "Living Room": ChibiRoboRegionData([], ["Living Room - Kitchen", "Living Room - Foyer", "Living Room - Backyard", "Living Room - Chibi House"]),
        "Chibi House": ChibiRoboRegionData([], ["Chibi House - Living Room" ]),
        "Kitchen": ChibiRoboRegionData([], ["Kitchen - Living Room", "Kitchen - Sink Drain", "Kitchen - Foyer" ]),
        "Sink Drain": ChibiRoboRegionData([], ["Sink Drain - Kitchen"]),
        "Backyard": ChibiRoboRegionData([], ["Backyard - Living Room", "UFO" ]),
        "Foyer": ChibiRoboRegionData([], ["Foyer - Living Room", "Foyer - Basement", "Foyer - Jenny's Room", "Foyer - Bedroom", "Foyer - Kitchen" ]),
        "Basement": ChibiRoboRegionData([], ["Basement - Foyer" ]),
        "Jenny's Room": ChibiRoboRegionData([], ["Jenny's Room - Foyer"]),
        "Bedroom": ChibiRoboRegionData([], ["Bedroom - Foyer"]),
        "UFO": ChibiRoboRegionData([], ["UFO - Backyard", "UFO - Bedroom - Past"]),
        "Bedroom - Past": ChibiRoboRegionData([], ["Bedroom - Past - UFO"]),
        "Mother Spider": ChibiRoboRegionData([], ["Mother Spider - Living Room", "Mother Spider - Staff Credit"]),
        "Staff Credit": ChibiRoboRegionData([], ["Staff Credit - Living Room"]),
    }

    # Living Room 67 Locations
    regions["Living Room"].locations.append("Living Room Frog Ring (Behind Window)")
    regions["Living Room"].locations.append("Living Room Frog Ring (Corkboard)")
    regions["Living Room"].locations.append("Living Room Frog Ring (Shelf)")
    regions["Living Room"].locations.append("Living Room Table 10M Coin")
    regions["Living Room"].locations.append("Living Room Under Bookshelf 10M Coin")
    regions["Living Room"].locations.append("Living Room Under TV 10M Coin")
    regions["Living Room"].locations.append("Living Room Bookshelf 10M Coin A")
    regions["Living Room"].locations.append("Living RoomBookshelf 10M Coin B")
    regions["Living Room"].locations.append("Living Room Armchair 10M Coin")
    regions["Living Room"].locations.append("Living Room Under Couch 10M Coin")
    regions["Living Room"].locations.append("Living Room Couch Backseat 10M Coin A")
    regions["Living Room"].locations.append("Living Room Couch Backseat 10M Coin B")
    regions["Living Room"].locations.append("Living Room Couch Backseat 10M Coin C")
    regions["Living Room"].locations.append("Living Room Cupholder 50M Coin")
    regions["Living Room"].locations.append("Living Room Plant Shelf 50M A")
    regions["Living Room"].locations.append("Living Room Plant Shelf 50M B")
    regions["Living Room"].locations.append("Living Room Plant Leaf 50M Coin")
    regions["Living Room"].locations.append("Living Room Wastepaper by Trashbin B")
    regions["Living Room"].locations.append("Living Room Candy Wrapper above Trashbin")
    regions["Living Room"].locations.append("Living Room Wastepaper by Trashbin A")
    regions["Living Room"].locations.append("Living Room Cupholder Wastepaper")
    regions["Living Room"].locations.append("Living Room Cookie Crumbs under Table")
    regions["Living Room"].locations.append("Living Room Cookie Crumbs by Record Player")
    regions["Living Room"].locations.append("Living Room Toothbrush")
    regions["Living Room"].locations.append("Living Room Armchair Happy Block")
    regions["Living Room"].locations.append("Living Room Bookshelf Happy Block (Lower)")
    regions["Living Room"].locations.append("Living Room Top of Record Player Shelving Happy Block")
    regions["Living Room"].locations.append("Living Room Bookshelf Happy Block (Upper)")
    regions["Living Room"].locations.append("Living Room Plant Shelf Happy Block (Lower)")
    regions["Living Room"].locations.append("Living Room Grandfather Clock Shelving Happy Block")
    regions["Living Room"].locations.append("Living Room Happy Block above Chibi-House")
    regions["Living Room"].locations.append("Living Room Plant Shelf Happy Block (Upper)")
    regions["Living Room"].locations.append("Living Room Happy Block above Fireplace")
    regions["Living Room"].locations.append("Living Room Happy Block by Record Player")
    regions["Living Room"].locations.append("Living Room Wastepaper by Door to Kitchen")
    regions["Living Room"].locations.append("Living Room Fireplace Wastepaper A")
    regions["Living Room"].locations.append("Living Room Fireplace Wastepaper B")
    regions["Living Room"].locations.append("Living Room Wastepaper on Stack of Books")
    regions["Living Room"].locations.append("Living Room Couch Wastepaper B")
    regions["Living Room"].locations.append("Living Room Armchair 50M Coin")
    regions["Living Room"].locations.append("Living Room Lamp 50M Coin")
    regions["Living Room"].locations.append("Living Room Wastepaper by Toothbrush Spawn")
    regions["Living Room"].locations.append("Living Room Wastepaper below Cupholder")
    regions["Living Room"].locations.append("Living Room Couch Wastepaper A")
    regions["Living Room"].locations.append("Living Room Cookie Crumbs under Couch")
    regions["Living Room"].locations.append("Living Room Cookie Crumbs on Couch")
    regions["Living Room"].locations.append("Living Room Twig A")
    regions["Living Room"].locations.append("Living Room Twig B")
    regions["Living Room"].locations.append("Living Room Twig C")
    regions["Living Room"].locations.append("Living Room 50M Coin on top of Chibi-House")
    regions["Living Room"].locations.append("Living Room Couch 10M Coin (Below Left Armrest)")
    regions["Living Room"].locations.append("Living Room 10M Coin behind Grandfather Clock Shelving A")
    regions["Living Room"].locations.append("Living Room 10M Coin behind Grandfather Clock Shelving B")
    regions["Living Room"].locations.append("Living Room 10M Coin behind Grandfather Clock Shelving C")
    regions["Living Room"].locations.append("Living Room Wastepaper above Trashbin A")
    regions["Living Room"].locations.append("Living Room Wastepaper above Trashbin B")
    regions["Living Room"].locations.append("Living Room Candy Wrapper by Jenny A")
    regions["Living Room"].locations.append("Living Room Candy Wrapper by Jenny B")
    regions["Living Room"].locations.append("Living Room Couch Candy Wrapper")
    regions["Living Room"].locations.append("Living Room Candy Wrapper on Book Stack")
    regions["Living Room"].locations.append("Living Room Armchair Candy Wrapper A")
    regions["Living Room"].locations.append("Living Room Armchair Candy Wrapper B")
    regions["Living Room"].locations.append("Living Room Cupholder Candy Wrapper")
    regions["Living Room"].locations.append("Living Room Couch Candy Bag")
    regions["Living Room"].locations.append("Living Room Table Cookie Box A")
    regions["Living Room"].locations.append("Living Room Table Cookie Box B")

    # Chibi House / Shop 13 Locations
    regions["Chibi House"].locations.append("Shop Pink Flower Seed")
    regions["Chibi House"].locations.append("Shop Blue Flower Seed")
    regions["Chibi House"].locations.append("Shop White Flower Seed")
    regions["Chibi House"].locations.append("Shop Nectar Flower Seed")
    regions["Chibi House"].locations.append("Shop Charge Chip")
    regions["Chibi House"].locations.append("Shop Chibi-Battery")
    regions["Chibi House"].locations.append("Shop Chibi-Blaster")
    regions["Chibi House"].locations.append("Shop Range Chip")
    regions["Chibi House"].locations.append("Shop Chibi-Radar")
    regions["Chibi House"].locations.append("Shop Alien Ear Chip")
    regions["Chibi House"].locations.append("Shop Hot Rod")
    regions["Chibi House"].locations.append("Shop Space Scrambler")

    # Kitchen 28 Locations
    regions["Kitchen"].locations.append("Kitchen Mug Location")
    regions["Kitchen"].locations.append("Kitchen Spoon Location")
    regions["Kitchen"].locations.append("Kitchen Wastepaper by Foyer Door")
    regions["Kitchen"].locations.append("Kitchen Wastepaper under Counter")
    regions["Kitchen"].locations.append("Kitchen Cookie Crumbs by Tao's Bowl")
    regions["Kitchen"].locations.append("Kitchen Cookie Crumbs by Spoon")
    regions["Kitchen"].locations.append("Kitchen Cookie Crumbs on Kitchen Table")
    regions["Kitchen"].locations.append("Kitchen Cookie Crumbs next to Fridge on Counter")
    regions["Kitchen"].locations.append("Kitchen Table Happy Block")
    regions["Kitchen"].locations.append("Kitchen Cabinet Happy Block")
    regions["Kitchen"].locations.append("Kitchen Happy Block above Bandage")
    regions["Kitchen"].locations.append("Kitchen Happy Block by Bridge-Only Chibi-Door")
    regions["Kitchen"].locations.append("Kitchen Twig A")
    regions["Kitchen"].locations.append("Kitchen Twig B")
    regions["Kitchen"].locations.append("Kitchen Twig C")
    regions["Kitchen"].locations.append("Kitchen Dog Tags Location")
    regions["Kitchen"].locations.append("Kitchen Bandage Location")
    regions["Kitchen"].locations.append("Kitchen Frog Ring (Table)")
    regions["Kitchen"].locations.append("Kitchen Pink Soda Can")
    regions["Kitchen"].locations.append("Kitchen Purple Soda Can")
    regions["Kitchen"].locations.append("Kitchen Table Candy Wrapper A")
    regions["Kitchen"].locations.append("Kitchen Table Candy Wrapper B")
    regions["Kitchen"].locations.append("Kitchen Table Candy Bag")
    regions["Kitchen"].locations.append("Kitchen Cookie Box by Spoon A")
    regions["Kitchen"].locations.append("Kitchen Cookie Box by Spoon B")
    regions["Kitchen"].locations.append("Kitchen High Cupboard 10M Coin")
    regions["Kitchen"].locations.append("Kitchen 10M Coin by Stove")
    regions["Kitchen"].locations.append("Kitchen 10M Coin by Sink")
    regions["Kitchen"].locations.append("Kitchen 10M behind Bottles")

    # Drain 10 Locations
    regions["Sink Drain"].locations.append("Sink Drain Middle Row 100M Coin A")
    regions["Sink Drain"].locations.append("Sink Drain Middle Row 100M Coin B")
    regions["Sink Drain"].locations.append("Sink Drain Middle Row 100M Coin C")
    regions["Sink Drain"].locations.append("Sink Drain Middle Row 10M Coin A")
    regions["Sink Drain"].locations.append("Sink Drain Middle Row 10M Coin B")
    regions["Sink Drain"].locations.append("Sink Drain Middle Row 10M Coin C")
    regions["Sink Drain"].locations.append("Sink Drain Top Row 100M Coin")
    regions["Sink Drain"].locations.append("Sink Drain Top Row 10M Coin A")
    regions["Sink Drain"].locations.append("Sink Drain Top Row 10M Coin B")
    regions["Sink Drain"].locations.append("Sink Drain Frog Ring")

    # Foyer 4 Locations
    regions["Foyer"].locations.append("Foyer Top of Stairs 10M Coin")
    regions["Foyer"].locations.append("Foyer Free Rangers Photo")
    regions["Foyer"].locations.append("Foyer Waterfall Frog Ring")
    regions["Foyer"].locations.append("Foyer Red Block")

    # Basement 21 Locations
    regions["Basement"].locations.append("Basement Giga-Battery")
    regions["Basement"].locations.append("Basement Giga-Charger")
    regions["Basement"].locations.append("Basement Wine Bottle A")
    regions["Basement"].locations.append("Basement Wine Bottle B")
    regions["Basement"].locations.append("Basement Wastepaper below Dresser")
    regions["Basement"].locations.append("Basement Wastepaper below Stairs")
    regions["Basement"].locations.append("Basement Wastepaper on Stairs")
    regions["Basement"].locations.append("Basement Wastepaper on Shelf")
    regions["Basement"].locations.append("Basement Broken Bottle Bottom")
    regions["Basement"].locations.append("Basement Broken Bottle Top")
    regions["Basement"].locations.append("Basement Gunpowder")
    regions["Basement"].locations.append("Basement Frog Ring")
    regions["Basement"].locations.append("Basement Purple Can")
    regions["Basement"].locations.append("Basement Cabinet Trash A")
    regions["Basement"].locations.append("Basement Cabinet Trash B")
    regions["Basement"].locations.append("Basement Shelf Happy Block A")
    regions["Basement"].locations.append("Basement Shelf Happy Block B")
    regions["Basement"].locations.append("Basement Rafters Happy Block A")
    regions["Basement"].locations.append("Basement Rafters Happy Block B")
    regions["Basement"].locations.append("Basement Stairs Happy Block")
    regions["Basement"].locations.append("Basement Swing 10M Coin")

    # Backyard 15 Locations
    regions["Backyard"].locations.append("Backyard Twig by Glass Door")
    regions["Backyard"].locations.append("Backyard Twig by Fence")
    regions["Backyard"].locations.append("Backyard Twig under Tree")
    regions["Backyard"].locations.append("Backyard Twig under Awning")
    regions["Backyard"].locations.append("Backyard Scurvy Splinter")
    regions["Backyard"].locations.append("Backyard Weeds A")
    regions["Backyard"].locations.append("Backyard Weeds B")
    regions["Backyard"].locations.append("Backyard Weeds C")
    regions["Backyard"].locations.append("Backyard Frog Ring")
    regions["Backyard"].locations.append("Backyard Right Awning Happy Block A")
    regions["Backyard"].locations.append("Backyard Right Awning Happy Block B")
    regions["Backyard"].locations.append("Backyard Right Awning Happy Block C")
    regions["Backyard"].locations.append("Backyard Left Awning Happy Block")
    regions["Backyard"].locations.append("Backyard Tree Happy Block")
    regions["Backyard"].locations.append("Backyard White Block")

    # Jenny's Room 52 Locations
    regions["Jenny's Room"].locations.append("Jenny's Room AA Battery")
    regions["Jenny's Room"].locations.append("Jenny's Room Happy Block by TV")
    regions["Jenny's Room"].locations.append("Jenny's Room Happy Block on Train Shelf B")
    regions["Jenny's Room"].locations.append("Jenny's Room Happy Block on Chair")
    regions["Jenny's Room"].locations.append("Jenny's Room Happy Block on Bookshelf")
    regions["Jenny's Room"].locations.append("Jenny's Room Happy Block on Train Shelf A")
    regions["Jenny's Room"].locations.append("Jenny's Room D Battery")
    regions["Jenny's Room"].locations.append("Jenny's Room C Battery")
    regions["Jenny's Room"].locations.append("Jenny's Room Wastepaper by Trashcan")
    regions["Jenny's Room"].locations.append("Jenny's Room Wastepaper by Piano")
    regions["Jenny's Room"].locations.append("Jenny's Room Wastepaper under Dresser")
    regions["Jenny's Room"].locations.append("Jenny's Room Wastepaper under Bed A")
    regions["Jenny's Room"].locations.append("Jenny's Room Wastepaper under Bed B")
    regions["Jenny's Room"].locations.append("Jenny's Room Wastepaper under Bed C")
    regions["Jenny's Room"].locations.append("Jenny's Room Wastepaper under Bed D")
    regions["Jenny's Room"].locations.append("Jenny's Room Wastepaper by Crayon Box")
    regions["Jenny's Room"].locations.append("Jenny's Room Red Shoe")
    regions["Jenny's Room"].locations.append("Jenny's Room Frog Ring")
    regions["Jenny's Room"].locations.append("Jenny's Room Squirter")
    regions["Jenny's Room"].locations.append("Jenny's Room Snorkel")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Crumbs under Bed A")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Crumbs under Bed B")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Crumbs under Bed C")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Crumbs under Bed D")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Crumbs by Chair")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Crumbs on Desk A")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Crumbs B")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Wrapper below Bed A")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Wrapper below Bed B")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Wrapper below Bed C")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Wrapper on Bed A")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Wrapper on Bed B")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Wrapper by TV")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Wrapper by Crayon Box A")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Wrapper by Crayon Box B")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Bag under Bed")
    regions["Jenny's Room"].locations.append("Jenny's Room Candy Bag on Bed")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Box under Bed A")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Box under Bed B")
    regions["Jenny's Room"].locations.append("Jenny's Room Cookie Box on Desk")
    regions["Jenny's Room"].locations.append("Jenny's Room Orange Can")
    regions["Jenny's Room"].locations.append("Jenny's Room Purple Can")
    regions["Jenny's Room"].locations.append("Jenny's Room Red Crayon")
    regions["Jenny's Room"].locations.append("Jenny's Room Yellow Crayon")
    regions["Jenny's Room"].locations.append("Jenny's Room Green Crayon")
    regions["Jenny's Room"].locations.append("Jenny's Room Purple Crayon")
    regions["Jenny's Room"].locations.append("Jenny's Room Green Block")
    regions["Jenny's Room"].locations.append("Jenny's Room Stool 10M Coin")
    regions["Jenny's Room"].locations.append("Jenny's Room Bed Railing 10M Coin B")
    regions["Jenny's Room"].locations.append("Jenny's Room Bed Railing 10M Coin A")
    regions["Jenny's Room"].locations.append("Jenny's Room Slide 10M Coin")
    regions["Jenny's Room"].locations.append("Jenny's Room 10M Coin under Castle")

    # Bedroom 24 Locations
    regions["Bedroom"].locations.append("Bedroom Dinahs Teeth")
    regions["Bedroom"].locations.append("Bedroom Left Leg in Suitcase")
    regions["Bedroom"].locations.append("Bedroom Ticket Stub")
    regions["Bedroom"].locations.append("Bedroom Passed-Out Frog")
    regions["Bedroom"].locations.append("Bedroom Wastepaper by Bills B")
    regions["Bedroom"].locations.append("Bedroom Wastepaper by Bills A")
    regions["Bedroom"].locations.append("Bedroom Wastepaper under Bed")
    regions["Bedroom"].locations.append("Bedroom Wastepaper under Vanity")
    regions["Bedroom"].locations.append("Bedroom Wastepaper on Vanity")
    regions["Bedroom"].locations.append("Bedroom Wastepaper on Bed")
    regions["Bedroom"].locations.append("Bedroom Wastepaper by Dinahs Place A")
    regions["Bedroom"].locations.append("Bedroom Wastepaper by Dinahs Place B")
    regions["Bedroom"].locations.append("Bedroom Cookie Crumbs on Toybox")
    regions["Bedroom"].locations.append("Bedroom Vanity Candy Wrapper A")
    regions["Bedroom"].locations.append("Bedroom Vanity Candy Wrapper B")
    regions["Bedroom"].locations.append("Bedroom Shelf Candy Wrapper")
    regions["Bedroom"].locations.append("Bedroom Vanity Candy Bag")
    regions["Bedroom"].locations.append("Bedroom Happy Block by Ticket Stub (Lower Shelf)")
    regions["Bedroom"].locations.append("Bedroom Happy Block by Ticket Stub (Higher Shelf)")
    regions["Bedroom"].locations.append("Bedroom Vanity Stool 10M Coin")
    regions["Bedroom"].locations.append("Bedroom 10M Coin by Dinahs Place")
    regions["Bedroom"].locations.append("Bedroom 10M Coin under Bed")
    regions["Bedroom"].locations.append("Bedroom 10M Coin on Nightstand")
    regions["Bedroom"].locations.append("Bedroom 10M Coin on Shelf")

    # Set up the regions correctly.
    for name, data in regions.items():
        multiworld.regions.append(create_region(multiworld, player, name, data))

def connect_entrances(multiworld: MultiWorld, player: int):
    multiworld.get_entrance("Menu - Living Room", player).connect(multiworld.get_region("Menu", player))
    multiworld.get_entrance("Living Room - Kitchen", player).connect(multiworld.get_region("Living Room", player))
    multiworld.get_entrance("Living Room - Foyer", player).connect(multiworld.get_region("Living Room", player))
    multiworld.get_entrance("Living Room - Backyard", player).connect(multiworld.get_region("Living Room", player))
    multiworld.get_entrance("Living Room - Chibi House", player).connect(multiworld.get_region("Living Room", player))
    multiworld.get_entrance("Chibi House - Living Room", player).connect(multiworld.get_region("Chibi House", player))
    multiworld.get_entrance("Kitchen - Living Room", player).connect(multiworld.get_region("Kitchen", player))
    multiworld.get_entrance("Kitchen - Foyer", player).connect(multiworld.get_region("Kitchen", player))
    multiworld.get_entrance("Kitchen - Sink Drain", player).connect(multiworld.get_region("Kitchen", player))
    multiworld.get_entrance("Sink Drain - Kitchen", player).connect(multiworld.get_region("Sink Drain", player))
    multiworld.get_entrance("Backyard - Living Room", player).connect(multiworld.get_region("Backyard", player))
    multiworld.get_entrance("UFO", player).connect(multiworld.get_region("Backyard", player))
    multiworld.get_entrance("Foyer - Living Room", player).connect(multiworld.get_region("Foyer", player))
    multiworld.get_entrance("Foyer - Basement", player).connect(multiworld.get_region("Foyer", player))
    multiworld.get_entrance("Foyer - Jenny's Room", player).connect(multiworld.get_region("Foyer", player))
    multiworld.get_entrance("Foyer - Bedroom", player).connect(multiworld.get_region("Foyer", player))
    multiworld.get_entrance("Foyer - Kitchen", player).connect(multiworld.get_region("Foyer", player))
    multiworld.get_entrance("Basement - Foyer", player).connect(multiworld.get_region("Basement", player))
    multiworld.get_entrance("Jenny's Room - Foyer", player).connect(multiworld.get_region("Jenny's Room", player))
    multiworld.get_entrance("Bedroom - Foyer", player).connect(multiworld.get_region("Bedroom", player))
    multiworld.get_entrance("UFO - Backyard", player).connect(multiworld.get_region("UFO", player))
    multiworld.get_entrance("UFO - Bedroom - Past", player).connect(multiworld.get_region("UFO", player))
    multiworld.get_entrance("Bedroom - Past - UFO", player).connect(multiworld.get_region("Bedroom - Past", player))
    multiworld.get_entrance("Mother Spider - Living Room", player).connect(multiworld.get_region("Mother Spider", player))
    multiworld.get_entrance("Mother Spider - Staff Credit", player).connect(multiworld.get_region("Mother Spider", player))
    multiworld.get_entrance("Staff Credit - Living Room", player).connect(multiworld.get_region("Staff Credit", player))

def create_region(multiworld: MultiWorld, player: int, name: str, data: ChibiRoboRegionData):
    region = Region(name, player, multiworld)
    if data.locations:
        for loc_name in data.locations:
            loc_data = LOCATION_TABLE.get(loc_name)
            location = ChibiRoboLocation(player, loc_name, region, ChibiRobobLocationData( 99, "Unknown", 0x7, 0x80000000))
            region.locations.append(location)

    if data.region_exits:
        for exit in data.region_exits:
            entrance = Entrance(player, exit, region)
            region.exits.append(entrance)

    return region

